version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: monaco-editor
    versions:
    - 0.22.1
    - 0.22.3
  - dependency-name: elliptic
    versions:
    - 6.5.3
